insert into public.flags (text, slug, type, language, votes, upvotes, downvotes, status, is_seed) values
  ('They listen without turning everything back to themselves.', 'they-listen-without-turning-everything-back-to-themselves', 'green', 'en', 5, 5, 0, 'approved', true),
  ('They remember the small details you mention days later.', 'they-remember-the-small-details-you-mention-days-later', 'green', 'en', 5, 6, 1, 'approved', true),
  ('They respect your schedule instead of acting entitled to your time.', 'they-respect-your-schedule-instead-of-acting-entitled-to-your-time', 'green', 'en', 5, 7, 2, 'approved', true),
  ('They can apologize clearly without becoming defensive.', 'they-can-apologize-clearly-without-becoming-defensive', 'green', 'en', 5, 8, 3, 'approved', true),
  ('They are kind to staff, drivers, and strangers.', 'they-are-kind-to-staff-drivers-and-strangers', 'green', 'en', 9, 9, 0, 'approved', true),
  ('They make plans and follow through on them.', 'they-make-plans-and-follow-through-on-them', 'green', 'en', 9, 10, 1, 'approved', true),
  ('They celebrate your wins without getting weird about it.', 'they-celebrate-your-wins-without-getting-weird-about-it', 'green', 'en', 9, 11, 2, 'approved', true),
  ('They ask how you feel and actually wait for the answer.', 'they-ask-how-you-feel-and-actually-wait-for-the-answer', 'green', 'en', 9, 12, 3, 'approved', true),
  ('They are consistent in public and in private.', 'they-are-consistent-in-public-and-in-private', 'green', 'en', 13, 13, 0, 'approved', true),
  ('They do not punish you for having boundaries.', 'they-do-not-punish-you-for-having-boundaries', 'green', 'en', 4, 5, 1, 'approved', true),
  ('They can handle feedback without turning it into a fight.', 'they-can-handle-feedback-without-turning-it-into-a-fight', 'green', 'en', 4, 6, 2, 'approved', true),
  ('They tell the truth even when the truth is awkward.', 'they-tell-the-truth-even-when-the-truth-is-awkward', 'green', 'en', 4, 7, 3, 'approved', true),
  ('They speak about past relationships with nuance and accountability.', 'they-speak-about-past-relationships-with-nuance-and-accountability', 'green', 'en', 8, 8, 0, 'approved', true),
  ('They check in when they know you had a hard day.', 'they-check-in-when-they-know-you-had-a-hard-day', 'green', 'en', 8, 9, 1, 'approved', true),
  ('They never make you feel silly for asking a direct question.', 'they-never-make-you-feel-silly-for-asking-a-direct-question', 'green', 'en', 8, 10, 2, 'approved', true),
  ('They communicate changes early instead of disappearing.', 'they-communicate-changes-early-instead-of-disappearing', 'green', 'en', 8, 11, 3, 'approved', true),
  ('They match effort without making it transactional.', 'they-match-effort-without-making-it-transactional', 'green', 'en', 12, 12, 0, 'approved', true),
  ('They make room for your friendships and personal life.', 'they-make-room-for-your-friendships-and-personal-life', 'green', 'en', 12, 13, 1, 'approved', true),
  ('They do not flirt with confusion just to feel powerful.', 'they-do-not-flirt-with-confusion-just-to-feel-powerful', 'green', 'en', 3, 5, 2, 'approved', true),
  ('They repair after conflict instead of pretending nothing happened.', 'they-repair-after-conflict-instead-of-pretending-nothing-happened', 'green', 'en', 3, 6, 3, 'approved', true),
  ('They can be warm without becoming overwhelming.', 'they-can-be-warm-without-becoming-overwhelming', 'green', 'en', 7, 7, 0, 'approved', true),
  ('They respect a slow pace and do not rush intimacy.', 'they-respect-a-slow-pace-and-do-not-rush-intimacy', 'green', 'en', 7, 8, 1, 'approved', true),
  ('They are curious about your perspective, not just your availability.', 'they-are-curious-about-your-perspective-not-just-your-availability', 'green', 'en', 7, 9, 2, 'approved', true),
  ('They notice when you seem off and ask gently.', 'they-notice-when-you-seem-off-and-ask-gently', 'green', 'en', 7, 10, 3, 'approved', true),
  ('They make honesty feel safe, not risky.', 'they-make-honesty-feel-safe-not-risky', 'green', 'en', 11, 11, 0, 'approved', true),
  ('Il ou elle respecte ton temps sans te culpabiliser.', 'il-ou-elle-respecte-ton-temps-sans-te-culpabiliser', 'green', 'fr', 11, 12, 1, 'approved', true),
  ('Il ou elle annonce les changements de plan assez tôt.', 'il-ou-elle-annonce-les-changements-de-plan-assez-tot', 'green', 'fr', 11, 13, 2, 'approved', true),
  ('Il ou elle écoute vraiment au lieu de juste répondre.', 'il-ou-elle-ecoute-vraiment-au-lieu-de-juste-repondre', 'green', 'fr', 2, 5, 3, 'approved', true),
  ('Il ou elle sait dire pardon sans détourner la conversation.', 'il-ou-elle-sait-dire-pardon-sans-detourner-la-conversation', 'green', 'fr', 6, 6, 0, 'approved', true),
  ('Il ou elle est poli avec tout le monde, pas seulement avec toi.', 'il-ou-elle-est-poli-avec-tout-le-monde-pas-seulement-avec-toi', 'green', 'fr', 6, 7, 1, 'approved', true),
  ('Il ou elle pose des questions de relance et s’en souvient plus tard.', 'il-ou-elle-pose-des-questions-de-relance-et-sen-souvient-plus-tard', 'green', 'fr', 6, 8, 2, 'approved', true),
  ('Il ou elle ne joue pas avec le flou pour garder l’avantage.', 'il-ou-elle-ne-joue-pas-avec-le-flou-pour-garder-lavantage', 'green', 'fr', 6, 9, 3, 'approved', true),
  ('Il ou elle respecte tes limites dès la première fois.', 'il-ou-elle-respecte-tes-limites-des-la-premiere-fois', 'green', 'fr', 10, 10, 0, 'approved', true),
  ('Il ou elle suit ses promesses même sur de petits détails.', 'il-ou-elle-suit-ses-promesses-meme-sur-de-petits-details', 'green', 'fr', 10, 11, 1, 'approved', true),
  ('Il ou elle peut gérer un désaccord sans te rabaisser.', 'il-ou-elle-peut-gerer-un-desaccord-sans-te-rabaisser', 'green', 'fr', 10, 12, 2, 'approved', true),
  ('Il ou elle te laisse de l’espace sans froideur punitive.', 'il-ou-elle-te-laisse-de-lespace-sans-froideur-punitive', 'green', 'fr', 10, 13, 3, 'approved', true),
  ('Il ou elle est cohérent entre les messages et les actes.', 'il-ou-elle-est-coherent-entre-les-messages-et-les-actes', 'green', 'fr', 5, 5, 0, 'approved', true),
  ('Il ou elle célèbre tes réussites sans jalousie cachée.', 'il-ou-elle-celebre-tes-reussites-sans-jalousie-cachee', 'green', 'fr', 5, 6, 1, 'approved', true),
  ('Il ou elle parle clairement de ses intentions.', 'il-ou-elle-parle-clairement-de-ses-intentions', 'green', 'fr', 5, 7, 2, 'approved', true),
  ('Il ou elle assume ses erreurs et ajuste son comportement.', 'il-ou-elle-assume-ses-erreurs-et-ajuste-son-comportement', 'green', 'fr', 5, 8, 3, 'approved', true),
  ('Il ou elle ne se moque pas de ta sensibilité.', 'il-ou-elle-ne-se-moque-pas-de-ta-sensibilite', 'green', 'fr', 9, 9, 0, 'approved', true),
  ('Il ou elle sait te rassurer sans faire de grandes promesses vides.', 'il-ou-elle-sait-te-rassurer-sans-faire-de-grandes-promesses-vides', 'green', 'fr', 9, 10, 1, 'approved', true),
  ('Il ou elle te traite avec le même respect en public et en privé.', 'il-ou-elle-te-traite-avec-le-meme-respect-en-public-et-en-prive', 'green', 'fr', 9, 11, 2, 'approved', true),
  ('Il ou elle protège ton sommeil, ton travail et ton calme.', 'il-ou-elle-protege-ton-sommeil-ton-travail-et-ton-calme', 'green', 'fr', 9, 12, 3, 'approved', true),
  ('Il ou elle sait écouter sans tout ramener à lui ou elle.', 'il-ou-elle-sait-ecouter-sans-tout-ramener-a-lui-ou-elle', 'green', 'fr', 13, 13, 0, 'approved', true),
  ('Il ou elle te laisse finir tes phrases sans couper.', 'il-ou-elle-te-laisse-finir-tes-phrases-sans-couper', 'green', 'fr', 4, 5, 1, 'approved', true),
  ('Il ou elle n’utilise pas l’humour pour humilier.', 'il-ou-elle-nutilise-pas-lhumour-pour-humilier', 'green', 'fr', 4, 6, 2, 'approved', true),
  ('Il ou elle fait sentir que la clarté est normale.', 'il-ou-elle-fait-sentir-que-la-clarte-est-normale', 'green', 'fr', 4, 7, 3, 'approved', true),
  ('Il ou elle prend soin du lien même après un conflit.', 'il-ou-elle-prend-soin-du-lien-meme-apres-un-conflit', 'green', 'fr', 8, 8, 0, 'approved', true),
  ('Il ou elle est stable sans être contrôlant.', 'il-ou-elle-est-stable-sans-etre-controlant', 'green', 'fr', 8, 9, 1, 'approved', true),
  ('They only text when they want attention, not connection.', 'they-only-text-when-they-want-attention-not-connection', 'red', 'en', 8, 10, 2, 'approved', true),
  ('They disappear for days and return like nothing happened.', 'they-disappear-for-days-and-return-like-nothing-happened', 'red', 'en', 8, 11, 3, 'approved', true),
  ('They mock your boundaries and call it humor.', 'they-mock-your-boundaries-and-call-it-humor', 'red', 'en', 12, 12, 0, 'approved', true),
  ('They are rude to staff for no reason.', 'they-are-rude-to-staff-for-no-reason', 'red', 'en', 12, 13, 1, 'approved', true),
  ('They speak with contempt about every ex.', 'they-speak-with-contempt-about-every-ex', 'red', 'en', 3, 5, 2, 'approved', true),
  ('They avoid direct questions with vague charm.', 'they-avoid-direct-questions-with-vague-charm', 'red', 'en', 3, 6, 3, 'approved', true),
  ('They guilt-trip you for needing space.', 'they-guilt-trip-you-for-needing-space', 'red', 'en', 7, 7, 0, 'approved', true),
  ('They want instant intimacy but offer no consistency.', 'they-want-instant-intimacy-but-offer-no-consistency', 'red', 'en', 7, 8, 1, 'approved', true),
  ('They get warmer only when they feel you pulling away.', 'they-get-warmer-only-when-they-feel-you-pulling-away', 'red', 'en', 7, 9, 2, 'approved', true),
  ('They make promises in the moment and forget them later.', 'they-make-promises-in-the-moment-and-forget-them-later', 'red', 'en', 7, 10, 3, 'approved', true),
  ('They keep score on every emotional gesture.', 'they-keep-score-on-every-emotional-gesture', 'red', 'en', 11, 11, 0, 'approved', true),
  ('They act supportive in private and dismissive in public.', 'they-act-supportive-in-private-and-dismissive-in-public', 'red', 'en', 11, 12, 1, 'approved', true),
  ('They make you feel dramatic for reacting to obvious disrespect.', 'they-make-you-feel-dramatic-for-reacting-to-obvious-disrespect', 'red', 'en', 11, 13, 2, 'approved', true),
  ('They blame confusion on you while creating the confusion.', 'they-blame-confusion-on-you-while-creating-the-confusion', 'red', 'en', 2, 5, 3, 'approved', true),
  ('They expect access to your time without planning anything.', 'they-expect-access-to-your-time-without-planning-anything', 'red', 'en', 6, 6, 0, 'approved', true),
  ('They use your vulnerability as content for jokes.', 'they-use-your-vulnerability-as-content-for-jokes', 'red', 'en', 6, 7, 1, 'approved', true),
  ('They only apologize when consequences are close.', 'they-only-apologize-when-consequences-are-close', 'red', 'en', 6, 8, 2, 'approved', true),
  ('They ask for patience while repeating the same pattern.', 'they-ask-for-patience-while-repeating-the-same-pattern', 'red', 'en', 6, 9, 3, 'approved', true),
  ('They flirt with other options just to feel in control.', 'they-flirt-with-other-options-just-to-feel-in-control', 'red', 'en', 10, 10, 0, 'approved', true),
  ('They disappear during hard moments and reappear for fun ones.', 'they-disappear-during-hard-moments-and-reappear-for-fun-ones', 'red', 'en', 10, 11, 1, 'approved', true),
  ('They turn every concern into a debate you have to win.', 'they-turn-every-concern-into-a-debate-you-have-to-win', 'red', 'en', 10, 12, 2, 'approved', true),
  ('They love being wanted more than they love being present.', 'they-love-being-wanted-more-than-they-love-being-present', 'red', 'en', 10, 13, 3, 'approved', true),
  ('They only become clear when they think they might lose access.', 'they-only-become-clear-when-they-think-they-might-lose-access', 'red', 'en', 5, 5, 0, 'approved', true),
  ('They talk about honesty but hate being questioned.', 'they-talk-about-honesty-but-hate-being-questioned', 'red', 'en', 5, 6, 1, 'approved', true),
  ('They make chaos feel normal and calm feel suspicious.', 'they-make-chaos-feel-normal-and-calm-feel-suspicious', 'red', 'en', 5, 7, 2, 'approved', true),
  ('Il ou elle disparaît puis revient seulement quand ça l’arrange.', 'il-ou-elle-disparait-puis-revient-seulement-quand-ca-larrange', 'red', 'fr', 5, 8, 3, 'approved', true),
  ('Il ou elle te culpabilise dès que tu poses une limite.', 'il-ou-elle-te-culpabilise-des-que-tu-poses-une-limite', 'red', 'fr', 9, 9, 0, 'approved', true),
  ('Il ou elle rabaisse les autres pour se sentir supérieur.', 'il-ou-elle-rabaisse-les-autres-pour-se-sentir-superieur', 'red', 'fr', 9, 10, 1, 'approved', true),
  ('Il ou elle transforme chaque question simple en brouillard.', 'il-ou-elle-transforme-chaque-question-simple-en-brouillard', 'red', 'fr', 9, 11, 2, 'approved', true),
  ('Il ou elle parle mal au personnel sans raison.', 'il-ou-elle-parle-mal-au-personnel-sans-raison', 'red', 'fr', 9, 12, 3, 'approved', true),
  ('Il ou elle veut ton énergie mais jamais la responsabilité.', 'il-ou-elle-veut-ton-energie-mais-jamais-la-responsabilite', 'red', 'fr', 13, 13, 0, 'approved', true),
  ('Il ou elle promet beaucoup puis devient introuvable.', 'il-ou-elle-promet-beaucoup-puis-devient-introuvable', 'red', 'fr', 4, 5, 1, 'approved', true),
  ('Il ou elle se vexe quand tu demandes de la clarté.', 'il-ou-elle-se-vexe-quand-tu-demandes-de-la-clarte', 'red', 'fr', 4, 6, 2, 'approved', true),
  ('Il ou elle ne revient vers toi que lorsqu’il ou elle s’ennuie.', 'il-ou-elle-ne-revient-vers-toi-que-lorsquil-ou-elle-sennuie', 'red', 'fr', 4, 7, 3, 'approved', true),
  ('Il ou elle fait des blagues qui reposent sur ton malaise.', 'il-ou-elle-fait-des-blagues-qui-reposent-sur-ton-malaise', 'red', 'fr', 8, 8, 0, 'approved', true),
  ('Il ou elle change de version selon ce qui l’avantage.', 'il-ou-elle-change-de-version-selon-ce-qui-lavantage', 'red', 'fr', 8, 9, 1, 'approved', true),
  ('Il ou elle attend de toi une disponibilité totale sans offrir de stabilité.', 'il-ou-elle-attend-de-toi-une-disponibilite-totale-sans-offrir-de-stabilite', 'red', 'fr', 8, 10, 2, 'approved', true),
  ('Il ou elle minimise toujours ton ressenti après t’avoir blessé.', 'il-ou-elle-minimise-toujours-ton-ressenti-apres-tavoir-blesse', 'red', 'fr', 8, 11, 3, 'approved', true),
  ('Il ou elle confond intensité et vraie implication.', 'il-ou-elle-confond-intensite-et-vraie-implication', 'red', 'fr', 12, 12, 0, 'approved', true),
  ('Il ou elle utilise le silence comme punition.', 'il-ou-elle-utilise-le-silence-comme-punition', 'red', 'fr', 12, 13, 1, 'approved', true),
  ('Il ou elle ne devient tendre que lorsqu’il ou elle te sent distant.', 'il-ou-elle-ne-devient-tendre-que-lorsquil-ou-elle-te-sent-distant', 'red', 'fr', 3, 5, 2, 'approved', true),
  ('Il ou elle critique tous ses ex sans jamais se remettre en question.', 'il-ou-elle-critique-tous-ses-ex-sans-jamais-se-remettre-en-question', 'red', 'fr', 3, 6, 3, 'approved', true),
  ('Il ou elle fait passer ton inconfort pour un manque d’humour.', 'il-ou-elle-fait-passer-ton-inconfort-pour-un-manque-dhumour', 'red', 'fr', 7, 7, 0, 'approved', true),
  ('Il ou elle exige la confiance sans offrir la transparence.', 'il-ou-elle-exige-la-confiance-sans-offrir-la-transparence', 'red', 'fr', 7, 8, 1, 'approved', true),
  ('Il ou elle crée du doute puis te reproche d’être perdu.', 'il-ou-elle-cree-du-doute-puis-te-reproche-detre-perdu', 'red', 'fr', 7, 9, 2, 'approved', true),
  ('Il ou elle apparaît pour les moments légers et fuit les conversations sérieuses.', 'il-ou-elle-apparait-pour-les-moments-legers-et-fuit-les-conversations-serieuses', 'red', 'fr', 7, 10, 3, 'approved', true),
  ('Il ou elle veut aller vite dès que tu réclames de la patience.', 'il-ou-elle-veut-aller-vite-des-que-tu-reclames-de-la-patience', 'red', 'fr', 11, 11, 0, 'approved', true),
  ('Il ou elle te donne l’impression de toujours devoir mériter le minimum.', 'il-ou-elle-te-donne-limpression-de-toujours-devoir-meriter-le-minimum', 'red', 'fr', 11, 12, 1, 'approved', true),
  ('Il ou elle transforme tes besoins en problème personnel.', 'il-ou-elle-transforme-tes-besoins-en-probleme-personnel', 'red', 'fr', 11, 13, 2, 'approved', true),
  ('Il ou elle rend le calme étrange parce que le chaos lui convient.', 'il-ou-elle-rend-le-calme-etrange-parce-que-le-chaos-lui-convient', 'red', 'fr', 2, 5, 3, 'approved', true);
